//  -*- mode:c++; indent-tabs-mode:t; tab-width:8; c-basic-offset:2; -*-
//  vi: noet ts=8 sw=2 cino=l1,g0,N-s,j1,U1,i4

/*
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

// Zero Copy Universal Library

#include <zlib/ZuUTF.hpp>

// generated by the following Perl script, using
// http://www.unicode.org/Public/12.0.0/ucd/EastAsianWidth.txt
// as an input

// #!/usr/bin/perl
// use Bit::Vector;
// $vec = Bit::Vector->new((1<<24));
// for $in (@ARGV) {
//   open(IN, "<$in") || die "$in: $!\n";
//   while ($_ = <IN>) {
//     chomp;
//     if (/^([0-9A-F]{4,6});(?:F|W)/) {
//       $vec->Bit_On(hex($1));
//     }
//     if (/^([0-9A-F]{4,6})\.\.([0-9A-F]{4,6});(?:F|W)/) {
//       $vec->Interval_Fill(hex($1), hex($2));
//     }
//   }
//   $start = 0;
//   while (($min, $max) = $vec->Interval_Scan_inc($start)) {
//     print "if (ZuLikely(u <  ", sprintf('0x%x', $min), ")) return 1;\n";
//     print "if (ZuLikely(u <= ", sprintf('0x%x', $max), ")) return 2;\n";
//     $start = $max + 1;
//   }
//   print "return 1;\n";
// }

unsigned ZuUTF32::width(uint32_t u)
{
  if (ZuLikely(u <  0x1100)) {
    if (ZuUnlikely(u < 0x20 || u == 0x7f)) return 2; // control characters
    return 1;
  }
  if (ZuLikely(u <= 0x115f)) return 2;
  if (ZuLikely(u <  0x231a)) return 1;
  if (ZuLikely(u <= 0x231b)) return 2;
  if (ZuLikely(u <  0x2329)) return 1;
  if (ZuLikely(u <= 0x232a)) return 2;
  if (ZuLikely(u <  0x23e9)) return 1;
  if (ZuLikely(u <= 0x23ec)) return 2;
  if (ZuLikely(u <  0x23f0)) return 1;
  if (ZuLikely(u <= 0x23f0)) return 2;
  if (ZuLikely(u <  0x23f3)) return 1;
  if (ZuLikely(u <= 0x23f3)) return 2;
  if (ZuLikely(u <  0x25fd)) return 1;
  if (ZuLikely(u <= 0x25fe)) return 2;
  if (ZuLikely(u <  0x2614)) return 1;
  if (ZuLikely(u <= 0x2615)) return 2;
  if (ZuLikely(u <  0x2648)) return 1;
  if (ZuLikely(u <= 0x2653)) return 2;
  if (ZuLikely(u <  0x267f)) return 1;
  if (ZuLikely(u <= 0x267f)) return 2;
  if (ZuLikely(u <  0x2693)) return 1;
  if (ZuLikely(u <= 0x2693)) return 2;
  if (ZuLikely(u <  0x26a1)) return 1;
  if (ZuLikely(u <= 0x26a1)) return 2;
  if (ZuLikely(u <  0x26aa)) return 1;
  if (ZuLikely(u <= 0x26ab)) return 2;
  if (ZuLikely(u <  0x26bd)) return 1;
  if (ZuLikely(u <= 0x26be)) return 2;
  if (ZuLikely(u <  0x26c4)) return 1;
  if (ZuLikely(u <= 0x26c5)) return 2;
  if (ZuLikely(u <  0x26ce)) return 1;
  if (ZuLikely(u <= 0x26ce)) return 2;
  if (ZuLikely(u <  0x26d4)) return 1;
  if (ZuLikely(u <= 0x26d4)) return 2;
  if (ZuLikely(u <  0x26ea)) return 1;
  if (ZuLikely(u <= 0x26ea)) return 2;
  if (ZuLikely(u <  0x26f2)) return 1;
  if (ZuLikely(u <= 0x26f3)) return 2;
  if (ZuLikely(u <  0x26f5)) return 1;
  if (ZuLikely(u <= 0x26f5)) return 2;
  if (ZuLikely(u <  0x26fa)) return 1;
  if (ZuLikely(u <= 0x26fa)) return 2;
  if (ZuLikely(u <  0x26fd)) return 1;
  if (ZuLikely(u <= 0x26fd)) return 2;
  if (ZuLikely(u <  0x2705)) return 1;
  if (ZuLikely(u <= 0x2705)) return 2;
  if (ZuLikely(u <  0x270a)) return 1;
  if (ZuLikely(u <= 0x270b)) return 2;
  if (ZuLikely(u <  0x2728)) return 1;
  if (ZuLikely(u <= 0x2728)) return 2;
  if (ZuLikely(u <  0x274c)) return 1;
  if (ZuLikely(u <= 0x274c)) return 2;
  if (ZuLikely(u <  0x274e)) return 1;
  if (ZuLikely(u <= 0x274e)) return 2;
  if (ZuLikely(u <  0x2753)) return 1;
  if (ZuLikely(u <= 0x2755)) return 2;
  if (ZuLikely(u <  0x2757)) return 1;
  if (ZuLikely(u <= 0x2757)) return 2;
  if (ZuLikely(u <  0x2795)) return 1;
  if (ZuLikely(u <= 0x2797)) return 2;
  if (ZuLikely(u <  0x27b0)) return 1;
  if (ZuLikely(u <= 0x27b0)) return 2;
  if (ZuLikely(u <  0x27bf)) return 1;
  if (ZuLikely(u <= 0x27bf)) return 2;
  if (ZuLikely(u <  0x2b1b)) return 1;
  if (ZuLikely(u <= 0x2b1c)) return 2;
  if (ZuLikely(u <  0x2b50)) return 1;
  if (ZuLikely(u <= 0x2b50)) return 2;
  if (ZuLikely(u <  0x2b55)) return 1;
  if (ZuLikely(u <= 0x2b55)) return 2;
  if (ZuLikely(u <  0x2e80)) return 1;
  if (ZuLikely(u <= 0x2e99)) return 2;
  if (ZuLikely(u <  0x2e9b)) return 1;
  if (ZuLikely(u <= 0x2ef3)) return 2;
  if (ZuLikely(u <  0x2f00)) return 1;
  if (ZuLikely(u <= 0x2fd5)) return 2;
  if (ZuLikely(u <  0x2ff0)) return 1;
  if (ZuLikely(u <= 0x2ffb)) return 2;
  if (ZuLikely(u <  0x3000)) return 1;
  if (ZuLikely(u <= 0x303e)) return 2;
  if (ZuLikely(u <  0x3041)) return 1;
  if (ZuLikely(u <= 0x3096)) return 2;
  if (ZuLikely(u <  0x3099)) return 1;
  if (ZuLikely(u <= 0x30ff)) return 2;
  if (ZuLikely(u <  0x3105)) return 1;
  if (ZuLikely(u <= 0x312f)) return 2;
  if (ZuLikely(u <  0x3131)) return 1;
  if (ZuLikely(u <= 0x318e)) return 2;
  if (ZuLikely(u <  0x3190)) return 1;
  if (ZuLikely(u <= 0x31ba)) return 2;
  if (ZuLikely(u <  0x31c0)) return 1;
  if (ZuLikely(u <= 0x31e3)) return 2;
  if (ZuLikely(u <  0x31f0)) return 1;
  if (ZuLikely(u <= 0x321e)) return 2;
  if (ZuLikely(u <  0x3220)) return 1;
  if (ZuLikely(u <= 0x3247)) return 2;
  if (ZuLikely(u <  0x3250)) return 1;
  if (ZuLikely(u <= 0x32fe)) return 2;
  if (ZuLikely(u <  0x3300)) return 1;
  if (ZuLikely(u <= 0x4dbf)) return 2;
  if (ZuLikely(u <  0x4e00)) return 1;
  if (ZuLikely(u <= 0xa48c)) return 2;
  if (ZuLikely(u <  0xa490)) return 1;
  if (ZuLikely(u <= 0xa4c6)) return 2;
  if (ZuLikely(u <  0xa960)) return 1;
  if (ZuLikely(u <= 0xa97c)) return 2;
  if (ZuLikely(u <  0xac00)) return 1;
  if (ZuLikely(u <= 0xd7a3)) return 2;
  if (ZuLikely(u <  0xf900)) return 1;
  if (ZuLikely(u <= 0xfaff)) return 2;
  if (ZuLikely(u <  0xfe10)) return 1;
  if (ZuLikely(u <= 0xfe19)) return 2;
  if (ZuLikely(u <  0xfe30)) return 1;
  if (ZuLikely(u <= 0xfe52)) return 2;
  if (ZuLikely(u <  0xfe54)) return 1;
  if (ZuLikely(u <= 0xfe66)) return 2;
  if (ZuLikely(u <  0xfe68)) return 1;
  if (ZuLikely(u <= 0xfe6b)) return 2;
  if (ZuLikely(u <  0xff01)) return 1;
  if (ZuLikely(u <= 0xff60)) return 2;
  if (ZuLikely(u <  0xffe0)) return 1;
  if (ZuLikely(u <= 0xffe6)) return 2;
  if (ZuLikely(u <  0x16fe0)) return 1;
  if (ZuLikely(u <= 0x16fe3)) return 2;
  if (ZuLikely(u <  0x17000)) return 1;
  if (ZuLikely(u <= 0x187f7)) return 2;
  if (ZuLikely(u <  0x18800)) return 1;
  if (ZuLikely(u <= 0x18af2)) return 2;
  if (ZuLikely(u <  0x1b000)) return 1;
  if (ZuLikely(u <= 0x1b11e)) return 2;
  if (ZuLikely(u <  0x1b150)) return 1;
  if (ZuLikely(u <= 0x1b152)) return 2;
  if (ZuLikely(u <  0x1b164)) return 1;
  if (ZuLikely(u <= 0x1b167)) return 2;
  if (ZuLikely(u <  0x1b170)) return 1;
  if (ZuLikely(u <= 0x1b2fb)) return 2;
  if (ZuLikely(u <  0x1f004)) return 1;
  if (ZuLikely(u <= 0x1f004)) return 2;
  if (ZuLikely(u <  0x1f0cf)) return 1;
  if (ZuLikely(u <= 0x1f0cf)) return 2;
  if (ZuLikely(u <  0x1f18e)) return 1;
  if (ZuLikely(u <= 0x1f18e)) return 2;
  if (ZuLikely(u <  0x1f191)) return 1;
  if (ZuLikely(u <= 0x1f19a)) return 2;
  if (ZuLikely(u <  0x1f200)) return 1;
  if (ZuLikely(u <= 0x1f202)) return 2;
  if (ZuLikely(u <  0x1f210)) return 1;
  if (ZuLikely(u <= 0x1f23b)) return 2;
  if (ZuLikely(u <  0x1f240)) return 1;
  if (ZuLikely(u <= 0x1f248)) return 2;
  if (ZuLikely(u <  0x1f250)) return 1;
  if (ZuLikely(u <= 0x1f251)) return 2;
  if (ZuLikely(u <  0x1f260)) return 1;
  if (ZuLikely(u <= 0x1f265)) return 2;
  if (ZuLikely(u <  0x1f300)) return 1;
  if (ZuLikely(u <= 0x1f320)) return 2;
  if (ZuLikely(u <  0x1f32d)) return 1;
  if (ZuLikely(u <= 0x1f335)) return 2;
  if (ZuLikely(u <  0x1f337)) return 1;
  if (ZuLikely(u <= 0x1f37c)) return 2;
  if (ZuLikely(u <  0x1f37e)) return 1;
  if (ZuLikely(u <= 0x1f393)) return 2;
  if (ZuLikely(u <  0x1f3a0)) return 1;
  if (ZuLikely(u <= 0x1f3ca)) return 2;
  if (ZuLikely(u <  0x1f3cf)) return 1;
  if (ZuLikely(u <= 0x1f3d3)) return 2;
  if (ZuLikely(u <  0x1f3e0)) return 1;
  if (ZuLikely(u <= 0x1f3f0)) return 2;
  if (ZuLikely(u <  0x1f3f4)) return 1;
  if (ZuLikely(u <= 0x1f3f4)) return 2;
  if (ZuLikely(u <  0x1f3f8)) return 1;
  if (ZuLikely(u <= 0x1f43e)) return 2;
  if (ZuLikely(u <  0x1f440)) return 1;
  if (ZuLikely(u <= 0x1f440)) return 2;
  if (ZuLikely(u <  0x1f442)) return 1;
  if (ZuLikely(u <= 0x1f4fc)) return 2;
  if (ZuLikely(u <  0x1f4ff)) return 1;
  if (ZuLikely(u <= 0x1f53d)) return 2;
  if (ZuLikely(u <  0x1f54b)) return 1;
  if (ZuLikely(u <= 0x1f54e)) return 2;
  if (ZuLikely(u <  0x1f550)) return 1;
  if (ZuLikely(u <= 0x1f567)) return 2;
  if (ZuLikely(u <  0x1f57a)) return 1;
  if (ZuLikely(u <= 0x1f57a)) return 2;
  if (ZuLikely(u <  0x1f595)) return 1;
  if (ZuLikely(u <= 0x1f596)) return 2;
  if (ZuLikely(u <  0x1f5a4)) return 1;
  if (ZuLikely(u <= 0x1f5a4)) return 2;
  if (ZuLikely(u <  0x1f5fb)) return 1;
  if (ZuLikely(u <= 0x1f64f)) return 2;
  if (ZuLikely(u <  0x1f680)) return 1;
  if (ZuLikely(u <= 0x1f6c5)) return 2;
  if (ZuLikely(u <  0x1f6cc)) return 1;
  if (ZuLikely(u <= 0x1f6cc)) return 2;
  if (ZuLikely(u <  0x1f6d0)) return 1;
  if (ZuLikely(u <= 0x1f6d2)) return 2;
  if (ZuLikely(u <  0x1f6d5)) return 1;
  if (ZuLikely(u <= 0x1f6d5)) return 2;
  if (ZuLikely(u <  0x1f6eb)) return 1;
  if (ZuLikely(u <= 0x1f6ec)) return 2;
  if (ZuLikely(u <  0x1f6f4)) return 1;
  if (ZuLikely(u <= 0x1f6fa)) return 2;
  if (ZuLikely(u <  0x1f7e0)) return 1;
  if (ZuLikely(u <= 0x1f7eb)) return 2;
  if (ZuLikely(u <  0x1f90d)) return 1;
  if (ZuLikely(u <= 0x1f971)) return 2;
  if (ZuLikely(u <  0x1f973)) return 1;
  if (ZuLikely(u <= 0x1f976)) return 2;
  if (ZuLikely(u <  0x1f97a)) return 1;
  if (ZuLikely(u <= 0x1f9a2)) return 2;
  if (ZuLikely(u <  0x1f9a5)) return 1;
  if (ZuLikely(u <= 0x1f9aa)) return 2;
  if (ZuLikely(u <  0x1f9ae)) return 1;
  if (ZuLikely(u <= 0x1f9ca)) return 2;
  if (ZuLikely(u <  0x1f9cd)) return 1;
  if (ZuLikely(u <= 0x1f9ff)) return 2;
  if (ZuLikely(u <  0x1fa70)) return 1;
  if (ZuLikely(u <= 0x1fa73)) return 2;
  if (ZuLikely(u <  0x1fa78)) return 1;
  if (ZuLikely(u <= 0x1fa7a)) return 2;
  if (ZuLikely(u <  0x1fa80)) return 1;
  if (ZuLikely(u <= 0x1fa82)) return 2;
  if (ZuLikely(u <  0x1fa90)) return 1;
  if (ZuLikely(u <= 0x1fa95)) return 2;
  if (ZuLikely(u <  0x20000)) return 1;
  if (ZuLikely(u <= 0x2fffd)) return 2;
  if (ZuLikely(u <  0x30000)) return 1;
  if (ZuLikely(u <= 0x3fffd)) return 2;
  return 1;
}
